### ISSUE TITLE
Unable to use ComplexFinder

### ISSUE THREAD

**Issue by svalvaro** [hnolCol/ComplexFinder#4]
Hi @hnolCol, 

I would like to try this software, though I haven't succeeded in using it (Linux machine).

I did this part without problems:
```
#create virt env
python3 -m venv env
#activate
source env/bin/activate
#install packages from req file
pip install -r requirements.txt
```

Then after entering in the folder, importing the library returns the error:

```
from .src.main import ComplexFinder

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: attempted relative import with no known parent package
```

Am I doing something wrong?

Best,

**Comment by lukebotticelli** [comment]
How did you fix this? I am new to python and having the same problem

**Comment by svalvaro** [comment]
Hi @lukebotticelli,

The simplest way to make it work is to open the `/src/main.py` file and run your code from there.
